defaults: &defaults
  pool: 5
  timeout: 5000
  encoding: utf8
  adapter: sqlite3
  database: db/development.sqlite3

development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: escrit_development
  pool: 5
  username: <%= ENV['ESCRIT_DATABASE_USER'] %>
  password: <%= ENV['ESCRIT_DATABASE_PASSWORD'] %>

test: &test
  <<: *defaults

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: escrit_production
  pool: 5
  username: <%= ENV['ESCRIT_DATABASE_USER'] %>
  password: <%= ENV['ESCRIT_DATABASE_PASSWORD'] %>
