development:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: escrit_development
  pool: 5
  username: <%= ENV['ESCRIT_DATABASE_USER'] %>
  password: <%= ENV['ESCRIT_DATABASE_PASSWORD'] %>

test:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: escrit_test<%= ENV['TEST_ENV_NUMBER'] ? "_#{ENV['TEST_ENV_NUMBER']}" : '' %>
  pool: 5
  username: <%= ENV['ESCRIT_DATABASE_USER'] %>
  password: <%= ENV['ESCRIT_DATABASE_PASSWORD'] %>

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: escrit_production
  pool: 5
  username: <%= ENV['ESCRIT_DATABASE_USER'] %>
  password: <%= ENV['ESCRIT_DATABASE_PASSWORD'] %>
